<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3ec7b189-38f4-447f-a0a7-0ba6ab323b4f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_qa_view_package</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[1]/a[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="dropdown-menu\\ dropdown-menu-fit\\ dropdown-menu-right\\ show"] #qa-view-package</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'qa-view-package') and equals(@text,'View Package Information')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>qa-view-package</value>
        <webElementGuid>964fceba-e8a0-47cb-98af-21fba731f11b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>View Package Information</value>
        <webElementGuid>964fceba-e8a0-47cb-98af-21fba731f11b</webElementGuid>
    </webElementProperties>
</WebElementEntity>