<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f181e4e5-bd24-47b0-adb0-f70990756ae8</elementGuidId>
    <imagePath></imagePath>
    <name>td_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[4]/div[1]/div[2]/div[2]/table[1]/tbody[1]/tr[7]/td[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="odd\\ parent"] &gt; [class="default-\\ sorting_1"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>