<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1493e1b3-2b01-4bec-9b1c-8015c33082cb</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\\ btn-primary"]:nth-child(3)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'\u0627\u0644\u0645\u0639\u062a\u0645\u0631\u064a\u0646 \u0627\u0644\u0630\u064a\u0646 \u0644\u0645 \u064a\u0635\u062f\u0631 \u0644\u0647\u0645 \u062a\u0635\u0631\u064a\u062d')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>المعتمرين الذين لم يصدر لهم تصريح</value>
        <webElementGuid>c9749a18-677f-4899-a675-dfd41a38eed8</webElementGuid>
    </webElementProperties>
</WebElementEntity>