<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7ce176e2-3b94-4173-ad41-73bd6d850bc3</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\\ btn-primary\\ mr-2"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'\u0625\u0635\u062f\u0627\u0631 \u062a\u0635\u0631\u064a\u062d \u0646\u0633\u0643')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>إصدار تصريح نسك</value>
        <webElementGuid>964fceba-e8a0-47cb-98af-21fba731f11b</webElementGuid>
    </webElementProperties>
</WebElementEntity>