<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>654faab2-679a-4b52-b3ef-53e79655742c</elementGuidId>
    <imagePath></imagePath>
    <name>button_next_step</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/form[1]/div[5]/button[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\\ btn-brand\\ btn-md\\ btn-tall\\ btn-wide\\ kt-font-bold\\ kt-font-transform-u"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'NEXT STEP')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>NEXT STEP</value>
        <webElementGuid>964fceba-e8a0-47cb-98af-21fba731f11b</webElementGuid>
    </webElementProperties>
</WebElementEntity>