<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ef98c878-418a-4832-9378-aca0250afde2</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_th_thu_t_ti_t_ki_m_dung_l_ng_cho_ng_i</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/ul[1]/li[2]/div[2]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\\32 0240226180105825 [class="show-popup\\ visit-popup"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Th\u1ee7 thu\u1eadt ti\u1ebft ki\u1ec7m dung l\u01b0\u1ee3ng cho ng\u01b0\u1eddi d\xf9ng iPhone th\u01b0\u1eddng xuy\xean quay video')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Thủ thuật tiết kiệm dung lượng cho người dùng iPhone thường xuyên quay video</value>
        <webElementGuid>ad5e3883-802b-40fd-98d2-08ae46f13b87</webElementGuid>
    </webElementProperties>
</WebElementEntity>