<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0b7ad469-1841-400d-95b6-806ff3ed6d1c</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_ra_m_t_macbook_air_2024_v_i_chip_m3_app</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[10]/div[2]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#newsid20240305115806467 [class="show-popup\\ visit-popup\\ inited-timeline-popup"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Ra m\u1eaft MacBook Air 2024 v\u1edbi chip M3, Apple cho th\u1ea5y \u0111ang "t\u1ea5t tay" v\u1edbi cu\u1ed9c ch\u01a1i AI nh\u01b0 th\u1ebf n\xe0o')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Ra mắt MacBook Air 2024 với chip M3, Apple cho thấy đang "tất tay" với cuộc chơi AI như thế nào</value>
        <webElementGuid>3160a716-5903-4c5e-b2b8-0b7679f46206</webElementGuid>
    </webElementProperties>
</WebElementEntity>