<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>214f018c-129f-46cc-944a-6d4dd5662d94</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_accessories</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/nav[1]/div[1]/ul[1]/li[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="horizontal-menu__element\ is-link\ is-root\ children-visible"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Accessories')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Accessories</value>
        <webElementGuid>7d09f94f-cc9e-4a13-9282-818bc2bbe03b</webElementGuid>
    </webElementProperties>
</WebElementEntity>