<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c8ae9e19-ea84-471d-9f6e-3d00c03d0ed2</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_g_n_3_th_p_k_l_m_vi_c_t_i_microsoft_c</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/ul[1]/li[7]/div[2]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\\32 024031210592242 [class="show-popup\\ visit-popup"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'G\u1ea7n 3 th\u1eadp k\u1ef7 l\xe0m vi\u1ec7c t\u1ea1i Microsoft, c\u1ef1u gi\xe1m \u0111\u1ed1c gi\u1ea3i th\xedch l\xfd t\u1ea1i sao Windows 11 l\u1ea1i ng\u1eebng h\u1ed7 tr\u1ee3 Android')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Gần 3 thập kỷ làm việc tại Microsoft, cựu giám đốc giải thích lý tại sao Windows 11 lại ngừng hỗ trợ Android</value>
        <webElementGuid>ad5e3883-802b-40fd-98d2-08ae46f13b87</webElementGuid>
    </webElementProperties>
</WebElementEntity>