<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b59d1890-f07d-4078-b786-6a64c59a3835</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_so_s_nh_galaxy_z_fold_6_v_galaxy_z_fold</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[3]/div[1]/div[2]/div[5]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[type="link_a"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'link_a') and equals(@text,'So s\xe1nh Galaxy Z Fold 6 v\xe0 Galaxy Z Fold 5: Thi\u1ebft k\u1ebf thay \u0111\u1ed5i ra sao?')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>So sánh Galaxy Z Fold 6 và Galaxy Z Fold 5: Thiết kế thay đổi ra sao?</value>
        <webElementGuid>964fceba-e8a0-47cb-98af-21fba731f11b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>link_a</value>
        <webElementGuid>964fceba-e8a0-47cb-98af-21fba731f11b</webElementGuid>
    </webElementProperties>
</WebElementEntity>