<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6c748e21-6942-4d64-bb98-d98f3e4ec0e4</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_internet</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/ul[1]/li[4]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="gmli"]:nth-child(4) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'INTERNET')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>INTERNET</value>
        <webElementGuid>0b098dbc-1ad3-46f4-bdeb-480cd62004e4</webElementGuid>
    </webElementProperties>
</WebElementEntity>