<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>350a8a95-9f67-47e0-8af5-5b2b1e438088</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_th_thu_t</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/ul[1]/li[7]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="gmli"]:nth-child(7) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'TH\u1ee6 THU\u1eacT')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>THỦ THUẬT</value>
        <webElementGuid>3160a716-5903-4c5e-b2b8-0b7679f46206</webElementGuid>
    </webElementProperties>
</WebElementEntity>