<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1ea9996a-d486-49e1-8e97-b4c07c04d9a7</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_b_youtuber_mkbhd_ch_bai_l_chi_c_xe_t</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/h3[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="klwfnswn\\ first"] [class="show-popup\\ visit-popup"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'B\u1ecb YouTuber MKBHD ch\xea bai l\xe0 "chi\u1ebfc xe t\u1ec7 nh\u1ea5t t\u1eebng \u0111\xe1nh gi\xe1", c\u1ed5 phi\u1ebfu m\u1ed9t h\xe3ng xe \u0111i\u1ec7n bay h\u01a1i 50%')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Bị YouTuber MKBHD chê bai là "chiếc xe tệ nhất từng đánh giá", cổ phiếu một hãng xe điện bay hơi 50%</value>
        <webElementGuid>964fceba-e8a0-47cb-98af-21fba731f11b</webElementGuid>
    </webElementProperties>
</WebElementEntity>