<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4477a2e0-63d5-4f94-b1b9-732a021257ec</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_samsung_ra_m_t_galaxy_s24_ultra_b_n_c</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[2]/div[1]/div[1]/h3[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-child(2) &gt; [type="midThumb"] h3 &gt; [class="gknews_title"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Samsung ra m\u1eaft Galaxy S24 Ultra b\u1ea3n \u0111\u1eb7c bi\u1ec7t: H\u1ed9p ph\u1ee5 ki\u1ec7n c\u1ef1c ch\u1ea5t, gi\u1edbi h\u1ea1n 2.000 chi\u1ebfc')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Samsung ra mắt Galaxy S24 Ultra bản đặc biệt: Hộp phụ kiện cực chất, giới hạn 2.000 chiếc</value>
        <webElementGuid>ad5e3883-802b-40fd-98d2-08ae46f13b87</webElementGuid>
    </webElementProperties>
</WebElementEntity>