<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9a3b7252-9eb6-46de-88ea-0ece9bad667f</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_startup_vi_t_coin98_s_p_nh_p_studio_chuy</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]/h3[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="cc"]:nth-child(1) &gt; h3 &gt; [class="show-popup\\ visit-popup"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Startup Vi\u1ec7t Coin98 s\xe1p nh\u1eadp studio chuy\xean v\u1ec1 game Yunero, h\u01b0\u1edbng t\u1edbi \u0111\u1ea9y m\u1ea1nh web3 v\xe0 GameFi')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Startup Việt Coin98 sáp nhập studio chuyên về game Yunero, hướng tới đẩy mạnh web3 và GameFi</value>
        <webElementGuid>ad5e3883-802b-40fd-98d2-08ae46f13b87</webElementGuid>
    </webElementProperties>
</WebElementEntity>