<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>465b2732-e91e-46ab-afab-603474a46d51</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_qa_actions_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[3]/div[2]/div[2]/table[1]/tbody[1]/tr[5]/td[1]/ul[1]/li[11]/span[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="child"]:nth-child(5) #qa-actions</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'qa-actions')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>qa-actions</value>
        <webElementGuid>964fceba-e8a0-47cb-98af-21fba731f11b</webElementGuid>
    </webElementProperties>
</WebElementEntity>