<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>431cfac9-29bb-4833-8f49-f3f5d5fe205c</elementGuidId>
    <imagePath></imagePath>
    <name>td_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[3]/div[2]/div[2]/table[1]/tbody[1]/tr[4]/td[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[role="row"]:nth-child(4) &gt; [class="\\ default-"]:nth-child(1)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>