<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>776dcb23-83a0-4897-b9a5-35089a0d53f7</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_delete</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="dropdown-menu\\ dropdown-menu-fit\\ dropdown-menu-right\\ show"] [class="kt-nav__item"]:nth-child(2)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Delete')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Delete</value>
        <webElementGuid>c9749a18-677f-4899-a675-dfd41a38eed8</webElementGuid>
    </webElementProperties>
</WebElementEntity>