<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8352a95b-4029-4bc5-ac8b-4983fb0f5a60</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_groups_management</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="kt-menu__nav\\ "] &gt; [class="kt-menu__item\\ \\ kt-menu__item--submenu"]:nth-child(3) &gt; [class="kt-menu__link\\ kt-menu__toggle"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Groups Management')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Groups Management</value>
        <webElementGuid>c9749a18-677f-4899-a675-dfd41a38eed8</webElementGuid>
    </webElementProperties>
</WebElementEntity>