<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fe0a5a07-17cb-4f82-909b-71725298dac9</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[3]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/form[1]/div[4]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/span[2]/span[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="select2-search\\ select2-search--dropdown"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry></entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>